[dependency-groups]
dev = [
    "google-generativeai>=0.8.6",
    "huggingface-hub>=0.36.0",
    "langchain>=1.2.0",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.2",
    "langchain-google-genai>=4.1.2",
    "langchain-huggingface>=1.2.0",
    "numpy>=2.3.5",
    "python-dotenv>=1.2.1",
    "scikit-learn>=1.8.0",
    "transformers>=4.57.3",
]
